// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.render.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Parameter group. */
@Fluent
public final class TileIndex {
    /*
     * X coordinate of the tile on zoom grid. Value must be in the range [0,
     * 2<sup>`zoom`</sup> -1].
     *
     * Please see [Zoom Levels and Tile
     * Grid](https://docs.microsoft.com/en-us/azure/location-based-services/zoom-levels-and-tile-grid)
     * for details.
     */
    @JsonProperty(value = "xTileIndex", required = true)
    private int xTileIndex;

    /*
     * Y coordinate of the tile on zoom grid. Value must be in the range [0,
     * 2<sup>`zoom`</sup> -1].
     *
     * Please see [Zoom Levels and Tile
     * Grid](https://docs.microsoft.com/en-us/azure/location-based-services/zoom-levels-and-tile-grid)
     * for details.
     */
    @JsonProperty(value = "yTileIndex", required = true)
    private int yTileIndex;

    /**
     * Get the xTileIndex property: X coordinate of the tile on zoom grid. Value must be in the range [0,
     * 2&lt;sup&gt;`zoom`&lt;/sup&gt; -1].
     *
     * <p>Please see [Zoom Levels and Tile
     * Grid](https://docs.microsoft.com/en-us/azure/location-based-services/zoom-levels-and-tile-grid) for details.
     *
     * @return the xTileIndex value.
     */
    public int getXTileIndex() {
        return this.xTileIndex;
    }

    /**
     * Set the xTileIndex property: X coordinate of the tile on zoom grid. Value must be in the range [0,
     * 2&lt;sup&gt;`zoom`&lt;/sup&gt; -1].
     *
     * <p>Please see [Zoom Levels and Tile
     * Grid](https://docs.microsoft.com/en-us/azure/location-based-services/zoom-levels-and-tile-grid) for details.
     *
     * @param xTileIndex the xTileIndex value to set.
     * @return the TileIndex object itself.
     */
    public TileIndex setXTileIndex(int xTileIndex) {
        this.xTileIndex = xTileIndex;
        return this;
    }

    /**
     * Get the yTileIndex property: Y coordinate of the tile on zoom grid. Value must be in the range [0,
     * 2&lt;sup&gt;`zoom`&lt;/sup&gt; -1].
     *
     * <p>Please see [Zoom Levels and Tile
     * Grid](https://docs.microsoft.com/en-us/azure/location-based-services/zoom-levels-and-tile-grid) for details.
     *
     * @return the yTileIndex value.
     */
    public int getYTileIndex() {
        return this.yTileIndex;
    }

    /**
     * Set the yTileIndex property: Y coordinate of the tile on zoom grid. Value must be in the range [0,
     * 2&lt;sup&gt;`zoom`&lt;/sup&gt; -1].
     *
     * <p>Please see [Zoom Levels and Tile
     * Grid](https://docs.microsoft.com/en-us/azure/location-based-services/zoom-levels-and-tile-grid) for details.
     *
     * @param yTileIndex the yTileIndex value to set.
     * @return the TileIndex object itself.
     */
    public TileIndex setYTileIndex(int yTileIndex) {
        this.yTileIndex = yTileIndex;
        return this;
    }
}
